<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('currencies', function (Blueprint $table) {
            $table->id();
            $table->char('currency_code', 3)->unique();
            $table->string('currency_name');
            $table->string('country');
            $table->timestamps();
        });
        DB::table('currencies')->insert([
            ['currency_code' => 'AED', 'currency_name' => 'UAE Dirham', 'country' => 'United Arab Emirates'],
            ['currency_code' => 'AFN', 'currency_name' => 'Afghani', 'country' => 'Afghanistan'],
            ['currency_code' => 'ALL', 'currency_name' => 'Lek', 'country' => 'Albania'],
            ['currency_code' => 'AMD', 'currency_name' => 'Armenian Dram', 'country' => 'Armenia'],
            ['currency_code' => 'ANG', 'currency_name' => 'Netherlands Antillian Guilder', 'country' => 'Netherlands Antilles'],
            ['currency_code' => 'AOA', 'currency_name' => 'Kwanza', 'country' => 'Angola'],
            ['currency_code' => 'ARS', 'currency_name' => 'Argentine Peso', 'country' => 'Argentina'],
            ['currency_code' => 'AUD', 'currency_name' => 'Australian Dollar', 'country' => 'Australia'],
            ['currency_code' => 'AWG', 'currency_name' => 'Aruban Guilder', 'country' => 'Aruba'],
            ['currency_code' => 'AZN', 'currency_name' => 'Azerbaijanian Manat', 'country' => 'Azerbaijan'],
            ['currency_code' => 'BAM', 'currency_name' => 'Convertible Marks', 'country' => 'Bosnia and Herzegovina'],
            ['currency_code' => 'BBD', 'currency_name' => 'Barbados Dollar', 'country' => 'Barbados'],
            ['currency_code' => 'BDT', 'currency_name' => 'Taka', 'country' => 'Bangladesh'],
            ['currency_code' => 'BGN', 'currency_name' => 'Bulgarian Lev', 'country' => 'Bulgaria'],
            ['currency_code' => 'BHD', 'currency_name' => 'Bahraini Dinar', 'country' => 'Bahrain'],
            ['currency_code' => 'BIF', 'currency_name' => 'Burundi Franc', 'country' => 'Burundi'],
            ['currency_code' => 'BMD', 'currency_name' => 'Bermudian Dollar', 'country' => 'Bermuda'],
            ['currency_code' => 'BND', 'currency_name' => 'Brunei Dollar', 'country' => 'Brunei'],
            ['currency_code' => 'BOB', 'currency_name' => 'Boliviano', 'country' => 'Bolivia'],
            ['currency_code' => 'BOV', 'currency_name' => 'Mvdol', 'country' => 'Bolivia'],
            ['currency_code' => 'BRL', 'currency_name' => 'Brazilian Real', 'country' => 'Brazil'],
            ['currency_code' => 'BSD', 'currency_name' => 'Bahamian Dollar', 'country' => 'Bahamas'],
            ['currency_code' => 'BTN', 'currency_name' => 'Ngultrum', 'country' => 'Bhutan'],
            ['currency_code' => 'BWP', 'currency_name' => 'Pula', 'country' => 'Botswana'],
            ['currency_code' => 'BYR', 'currency_name' => 'Belarussian Ruble', 'country' => 'Belarus'],
            ['currency_code' => 'BZD', 'currency_name' => 'Belize Dollar', 'country' => 'Belize'],
            ['currency_code' => 'CAD', 'currency_name' => 'Canadian Dollar', 'country' => 'Canada'],
            ['currency_code' => 'CDF', 'currency_name' => 'Congolese Franc', 'country' => 'Congo'],
            ['currency_code' => 'CHE', 'currency_name' => 'WIR Euro', 'country' => 'Switzerland'],
            ['currency_code' => 'CHF', 'currency_name' => 'Swiss Franc', 'country' => 'Switzerland'],
            ['currency_code' => 'CHW', 'currency_name' => 'WIR Franc', 'country' => 'Switzerland'],
            ['currency_code' => 'CLF', 'currency_name' => 'Unidades de fomento', 'country' => 'Chile'],
            ['currency_code' => 'CLP', 'currency_name' => 'Chilean Peso', 'country' => 'Chile'],
            ['currency_code' => 'CNY', 'currency_name' => 'Yuan Renminbi', 'country' => 'China'],
            ['currency_code' => 'COP', 'currency_name' => 'Colombian Peso', 'country' => 'Colombia'],
            ['currency_code' => 'COU', 'currency_name' => 'Unidad de Valor Real', 'country' => 'Colombia'],
            ['currency_code' => 'CRC', 'currency_name' => 'Costa Rican Colon', 'country' => 'Costa Rica'],
            ['currency_code' => 'CUC', 'currency_name' => 'Peso Convertible', 'country' => 'Cuba'],
            ['currency_code' => 'CUP', 'currency_name' => 'Cuban Peso', 'country' => 'Cuba'],
            ['currency_code' => 'CVE', 'currency_name' => 'Cape Verde Escudo', 'country' => 'Cape Verde'],
            ['currency_code' => 'CZK', 'currency_name' => 'Czech Koruna', 'country' => 'Czech Republic'],
            ['currency_code' => 'DJF', 'currency_name' => 'Djibouti Franc', 'country' => 'Djibouti'],
            ['currency_code' => 'DKK', 'currency_name' => 'Danish Krone', 'country' => 'Denmark'],
            ['currency_code' => 'DOP', 'currency_name' => 'Dominican Peso', 'country' => 'Dominican Republic'],
            ['currency_code' => 'DZD', 'currency_name' => 'Algerian Dinar', 'country' => 'Algeria'],
            ['currency_code' => 'EEK', 'currency_name' => 'Kroon', 'country' => 'Estonia'],
            ['currency_code' => 'EGP', 'currency_name' => 'Egyptian Pound', 'country' => 'Egypt'],
            ['currency_code' => 'ERN', 'currency_name' => 'Nakfa', 'country' => 'Eritrea'],
            ['currency_code' => 'ETB', 'currency_name' => 'Ethiopian Birr', 'country' => 'Ethiopia'],
            ['currency_code' => 'EUR', 'currency_name' => 'Euro', 'country' => 'European Union'],
            ['currency_code' => 'FJD', 'currency_name' => 'Fiji Dollar', 'country' => 'Fiji'],
            ['currency_code' => 'FKP', 'currency_name' => 'Falkland Islands Pound', 'country' => 'Falkland Islands'],
            ['currency_code' => 'GBP', 'currency_name' => 'Pound Sterling', 'country' => 'United Kingdom'],
            ['currency_code' => 'GEL', 'currency_name' => 'Lari', 'country' => 'Georgia'],
            ['currency_code' => 'GHS', 'currency_name' => 'Cedi', 'country' => 'Ghana'],
            ['currency_code' => 'GIP', 'currency_name' => 'Gibraltar Pound', 'country' => 'Gibraltar'],
            ['currency_code' => 'GMD', 'currency_name' => 'Dalasi', 'country' => 'Gambia'],
            ['currency_code' => 'GNF', 'currency_name' => 'Guinea Franc', 'country' => 'Guinea'],
            ['currency_code' => 'GTQ', 'currency_name' => 'Quetzal', 'country' => 'Guatemala'],
            ['currency_code' => 'GYD', 'currency_name' => 'Guyana Dollar', 'country' => 'Guyana'],
            ['currency_code' => 'HKD', 'currency_name' => 'Hong Kong Dollar', 'country' => 'Hong Kong'],
            ['currency_code' => 'HNL', 'currency_name' => 'Lempira', 'country' => 'Honduras'],
            ['currency_code' => 'HRK', 'currency_name' => 'Croatian Kuna', 'country' => 'Croatia'],
            ['currency_code' => 'HTG', 'currency_name' => 'Gourde', 'country' => 'Haiti'],
            ['currency_code' => 'HUF', 'currency_name' => 'Forint', 'country' => 'Hungary'],
            ['currency_code' => 'IDR', 'currency_name' => 'Rupiah', 'country' => 'Indonesia'],
            ['currency_code' => 'ILS', 'currency_name' => 'New Israeli Sheqel', 'country' => 'Israel'],
            ['currency_code' => 'INR', 'currency_name' => 'Indian Rupee', 'country' => 'India'],
            ['currency_code' => 'IQD', 'currency_name' => 'Iraqi Dinar', 'country' => 'Iraq'],
            ['currency_code' => 'IRR', 'currency_name' => 'Iranian Rial', 'country' => 'Iran'],
            ['currency_code' => 'ISK', 'currency_name' => 'Iceland Krona', 'country' => 'Iceland'],
            ['currency_code' => 'JMD', 'currency_name' => 'Jamaican Dollar', 'country' => 'Jamaica'],
            ['currency_code' => 'JOD', 'currency_name' => 'Jordanian Dinar', 'country' => 'Jordan'],
            ['currency_code' => 'JPY', 'currency_name' => 'Yen', 'country' => 'Japan'],
            ['currency_code' => 'KES', 'currency_name' => 'Kenyan Shilling', 'country' => 'Kenya'],
            ['currency_code' => 'KGS', 'currency_name' => 'Som', 'country' => 'Kyrgyzstan'],
            ['currency_code' => 'KHR', 'currency_name' => 'Riel', 'country' => 'Cambodia'],
            ['currency_code' => 'KMF', 'currency_name' => 'Comoro Franc', 'country' => 'Comoros'],
            ['currency_code' => 'KPW', 'currency_name' => 'North Korean Won', 'country' => 'North Korea'],
            ['currency_code' => 'KRW', 'currency_name' => 'Won', 'country' => 'South Korea'],
            ['currency_code' => 'KWD', 'currency_name' => 'Kuwaiti Dinar', 'country' => 'Kuwait'],
            ['currency_code' => 'KYD', 'currency_name' => 'Cayman Islands Dollar', 'country' => 'Cayman Islands'],
            ['currency_code' => 'KZT', 'currency_name' => 'Tenge', 'country' => 'Kazakhstan'],
            ['currency_code' => 'LAK', 'currency_name' => 'Kip', 'country' => 'Laos'],
            ['currency_code' => 'LBP', 'currency_name' => 'Lebanese Pound', 'country' => 'Lebanon'],
            ['currency_code' => 'LKR', 'currency_name' => 'Sri Lanka Rupee', 'country' => 'Sri Lanka'],
            ['currency_code' => 'LRD', 'currency_name' => 'Liberian Dollar', 'country' => 'Liberia'],
            ['currency_code' => 'LSL', 'currency_name' => 'Loti', 'country' => 'Lesotho'],
            ['currency_code' => 'LTL', 'currency_name' => 'Lithuanian Litas', 'country' => 'Lithuania'],
            ['currency_code' => 'LVL', 'currency_name' => 'Latvian Lats', 'country' => 'Latvia'],
            ['currency_code' => 'LYD', 'currency_name' => 'Libyan Dinar', 'country' => 'Libya'],
            ['currency_code' => 'MAD', 'currency_name' => 'Moroccan Dirham', 'country' => 'Morocco'],
            ['currency_code' => 'MDL', 'currency_name' => 'Moldovan Leu', 'country' => 'Moldova'],
            ['currency_code' => 'MGA', 'currency_name' => 'Malagasy Ariary', 'country' => 'Madagascar'],
            ['currency_code' => 'MKD', 'currency_name' => 'Denar', 'country' => 'North Macedonia'],
            ['currency_code' => 'MMK', 'currency_name' => 'Kyat', 'country' => 'Myanmar'],
            ['currency_code' => 'MNT', 'currency_name' => 'Tugrik', 'country' => 'Mongolia'],
            ['currency_code' => 'MOP', 'currency_name' => 'Pataca', 'country' => 'Macau'],
            ['currency_code' => 'MRO', 'currency_name' => 'Ouguiya', 'country' => 'Mauritania'],
            ['currency_code' => 'MUR', 'currency_name' => 'Mauritius Rupee', 'country' => 'Mauritius'],
            ['currency_code' => 'MVR', 'currency_name' => 'Rufiyaa', 'country' => 'Maldives'],
            ['currency_code' => 'MWK', 'currency_name' => 'Kwacha', 'country' => 'Malawi'],
            ['currency_code' => 'MXN', 'currency_name' => 'Mexican Peso', 'country' => 'Mexico'],
            ['currency_code' => 'MXV', 'currency_name' => 'Mexican Unidad de Inversion (UDI)', 'country' => 'Mexico'],
            ['currency_code' => 'MYR', 'currency_name' => 'Malaysian Ringgit', 'country' => 'Malaysia'],
            ['currency_code' => 'MZN', 'currency_name' => 'Metical', 'country' => 'Mozambique'],
            ['currency_code' => 'NAD', 'currency_name' => 'Namibia Dollar', 'country' => 'Namibia'],
            ['currency_code' => 'NGN', 'currency_name' => 'Naira', 'country' => 'Nigeria'],
            ['currency_code' => 'NIO', 'currency_name' => 'Cordoba Oro', 'country' => 'Nicaragua'],
            ['currency_code' => 'NOK', 'currency_name' => 'Norwegian Krone', 'country' => 'Norway'],
            ['currency_code' => 'NPR', 'currency_name' => 'Nepalese Rupee', 'country' => 'Nepal'],
            ['currency_code' => 'NZD', 'currency_name' => 'New Zealand Dollar', 'country' => 'New Zealand'],
            ['currency_code' => 'OMR', 'currency_name' => 'Rial Omani', 'country' => 'Oman'],
            ['currency_code' => 'PAB', 'currency_name' => 'Balboa', 'country' => 'Panama'],
            ['currency_code' => 'PEN', 'currency_name' => 'Nuevo Sol', 'country' => 'Peru'],
            ['currency_code' => 'PGK', 'currency_name' => 'Kina', 'country' => 'Papua New Guinea'],
            ['currency_code' => 'PHP', 'currency_name' => 'Philippine Peso', 'country' => 'Philippines'],
            ['currency_code' => 'PKR', 'currency_name' => 'Pakistan Rupee', 'country' => 'Pakistan'],
            ['currency_code' => 'PLN', 'currency_name' => 'Zloty', 'country' => 'Poland'],
            ['currency_code' => 'PYG', 'currency_name' => 'Guarani', 'country' => 'Paraguay'],
            ['currency_code' => 'QAR', 'currency_name' => 'Qatari Rial', 'country' => 'Qatar'],
            ['currency_code' => 'RON', 'currency_name' => 'New Leu', 'country' => 'Romania'],
            ['currency_code' => 'RSD', 'currency_name' => 'Serbian Dinar', 'country' => 'Serbia'],
            ['currency_code' => 'RUB', 'currency_name' => 'Russian Ruble', 'country' => 'Russia'],
            ['currency_code' => 'RWF', 'currency_name' => 'Rwanda Franc', 'country' => 'Rwanda'],
            ['currency_code' => 'SAR', 'currency_name' => 'Saudi Riyal', 'country' => 'Saudi Arabia'],
            ['currency_code' => 'SBD', 'currency_name' => 'Solomon Islands Dollar', 'country' => 'Solomon Islands'],
            ['currency_code' => 'SCR', 'currency_name' => 'Seychelles Rupee', 'country' => 'Seychelles'],
            ['currency_code' => 'SDG', 'currency_name' => 'Sudanese Pound', 'country' => 'Sudan'],
            ['currency_code' => 'SEK', 'currency_name' => 'Swedish Krona', 'country' => 'Sweden'],
            ['currency_code' => 'SGD', 'currency_name' => 'Singapore Dollar', 'country' => 'Singapore'],
            ['currency_code' => 'SHP', 'currency_name' => 'Saint Helena Pound', 'country' => 'Saint Helena'],
            ['currency_code' => 'SLL', 'currency_name' => 'Leone', 'country' => 'Sierra Leone'],
            ['currency_code' => 'SOS', 'currency_name' => 'Somali Shilling', 'country' => 'Somalia'],
            ['currency_code' => 'SRD', 'currency_name' => 'Surinam Dollar', 'country' => 'Suriname'],
            ['currency_code' => 'STD', 'currency_name' => 'Dobra', 'country' => 'Sao Tome and Principe'],
            ['currency_code' => 'SVC', 'currency_name' => 'El Salvador Colon', 'country' => 'El Salvador'],
            ['currency_code' => 'SYP', 'currency_name' => 'Syrian Pound', 'country' => 'Syria'],
            ['currency_code' => 'SZL', 'currency_name' => 'Lilangeni', 'country' => 'Eswatini'],
            ['currency_code' => 'THB', 'currency_name' => 'Baht', 'country' => 'Thailand'],
            ['currency_code' => 'TJS', 'currency_name' => 'Somoni', 'country' => 'Tajikistan'],
            ['currency_code' => 'TMT', 'currency_name' => 'Manat', 'country' => 'Turkmenistan'],
            ['currency_code' => 'TND', 'currency_name' => 'Tunisian Dinar', 'country' => 'Tunisia'],
            ['currency_code' => 'TOP', 'currency_name' => 'Pa\'anga', 'country' => 'Tonga'],
            ['currency_code' => 'TRY', 'currency_name' => 'Turkish Lira', 'country' => 'Turkey'],
            ['currency_code' => 'TTD', 'currency_name' => 'Trinidad and Tobago Dollar', 'country' => 'Trinidad and Tobago'],
            ['currency_code' => 'TWD', 'currency_name' => 'New Taiwan Dollar', 'country' => 'Taiwan'],
            ['currency_code' => 'TZS', 'currency_name' => 'Tanzanian Shilling', 'country' => 'Tanzania'],
            ['currency_code' => 'UAH', 'currency_name' => 'Hryvnia', 'country' => 'Ukraine'],
            ['currency_code' => 'UGX', 'currency_name' => 'Uganda Shilling', 'country' => 'Uganda'],
            ['currency_code' => 'USD', 'currency_name' => 'US Dollar', 'country' => 'United States'],
            ['currency_code' => 'USN', 'currency_name' => 'US Dollar (Next day)', 'country' => 'United States'],
            ['currency_code' => 'USS', 'currency_name' => 'US Dollar (Same day)', 'country' => 'United States'],
            ['currency_code' => 'UYI', 'currency_name' => 'Uruguay Peso en Unidades Indexadas', 'country' => 'Uruguay'],
            ['currency_code' => 'UYU', 'currency_name' => 'Peso Uruguayo', 'country' => 'Uruguay'],
            ['currency_code' => 'UZS', 'currency_name' => 'Uzbekistan Sum', 'country' => 'Uzbekistan'],
            ['currency_code' => 'VEF', 'currency_name' => 'Bolivar Fuerte', 'country' => 'Venezuela'],
            ['currency_code' => 'VND', 'currency_name' => 'Dong', 'country' => 'Vietnam'],
            ['currency_code' => 'VUV', 'currency_name' => 'Vatu', 'country' => 'Vanuatu'],
            ['currency_code' => 'WST', 'currency_name' => 'Tala', 'country' => 'Samoa'],
            ['currency_code' => 'XAF', 'currency_name' => 'CFA Franc BEAC', 'country' => 'Central African CFA'],
            ['currency_code' => 'XAG', 'currency_name' => 'Silver', 'country' => 'International'],
            ['currency_code' => 'XAU', 'currency_name' => 'Gold', 'country' => 'International'],
            ['currency_code' => 'XBA', 'currency_name' => 'Bond Markets Units European Composite Unit (EURCO)', 'country' => 'European Union'],
            ['currency_code' => 'XBB', 'currency_name' => 'European Monetary Unit (E.M.U.-6)', 'country' => 'European Union'],
            ['currency_code' => 'XBC', 'currency_name' => 'European Unit of Account 9(E.U.A.-9)', 'country' => 'European Union'],
            ['currency_code' => 'XBD', 'currency_name' => 'European Unit of Account 17(E.U.A.-17)', 'country' => 'European Union'],
            ['currency_code' => 'XCD', 'currency_name' => 'East Caribbean Dollar', 'country' => 'East Caribbean'],
            ['currency_code' => 'XDR', 'currency_name' => 'SDR', 'country' => 'International Monetary Fund'],
            ['currency_code' => 'XFU', 'currency_name' => 'UIC-Franc', 'country' => 'International'],
            ['currency_code' => 'XOF', 'currency_name' => 'CFA Franc BCEAO', 'country' => 'West African CFA'],
            ['currency_code' => 'XPD', 'currency_name' => 'Palladium', 'country' => 'International'],
            ['currency_code' => 'XPF', 'currency_name' => 'CFP Franc', 'country' => 'Pacific Franc'],
            ['currency_code' => 'XPT', 'currency_name' => 'Platinum', 'country' => 'International'],
            ['currency_code' => 'YER', 'currency_name' => 'Yemeni Rial', 'country' => 'Yemen'],
            ['currency_code' => 'ZAR', 'currency_name' => 'Rand', 'country' => 'South Africa'],
            ['currency_code' => 'ZMK', 'currency_name' => 'Zambian Kwacha', 'country' => 'Zambia'],
            ['currency_code' => 'ZWL', 'currency_name' => 'Zimbabwe Dollar', 'country' => 'Zimbabwe'],
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('currencies');
    }
};
